// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refreshtoken.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(token, userId, revokedAt) 
VALUES ($1, $2, $3) RETURNING token, created_on, updated_on, revokedat, userid
`

type CreateRefreshTokenParams struct {
	Token     string
	Userid    uuid.UUID
	Revokedat sql.NullTime
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.Userid, arg.Revokedat)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Revokedat,
		&i.Userid,
	)
	return i, err
}

const getTokenById = `-- name: GetTokenById :one
SELECT token, created_on, updated_on, revokedat, userid FROM refresh_tokens WHERE token=$1 LIMIT 1
`

func (q *Queries) GetTokenById(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenById, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Revokedat,
		&i.Userid,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET revokedAt=NOW() WHERE token=$1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
