// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tracks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const fetchAlbumTracks = `-- name: FetchAlbumTracks :many
SELECT id, youtubeid, name, spotifyduration, spotifyuri, isexplicit, isavailable, youtubeurltype, youtubeurl, fileurl, albumid, created_on, updated_on, spotifyid, tracknumber FROM tracks WHERE  (albumId = $1) ORDER BY trackNumber
`

func (q *Queries) FetchAlbumTracks(ctx context.Context, albumid sql.NullString) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, fetchAlbumTracks, albumid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Youtubeid,
			&i.Name,
			&i.Spotifyduration,
			&i.Spotifyuri,
			&i.Isexplicit,
			&i.Isavailable,
			&i.Youtubeurltype,
			&i.Youtubeurl,
			&i.Fileurl,
			&i.Albumid,
			&i.CreatedOn,
			&i.UpdatedOn,
			&i.Spotifyid,
			&i.Tracknumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchTrack = `-- name: FetchTrack :one
SELECT id, youtubeid, name, spotifyduration, spotifyuri, isexplicit, isavailable, youtubeurltype, youtubeurl, fileurl, albumid, created_on, updated_on, spotifyid, tracknumber FROM tracks WHERE (id = $1)
`

func (q *Queries) FetchTrack(ctx context.Context, id uuid.UUID) (Track, error) {
	row := q.db.QueryRowContext(ctx, fetchTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Youtubeid,
		&i.Name,
		&i.Spotifyduration,
		&i.Spotifyuri,
		&i.Isexplicit,
		&i.Isavailable,
		&i.Youtubeurltype,
		&i.Youtubeurl,
		&i.Fileurl,
		&i.Albumid,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Spotifyid,
		&i.Tracknumber,
	)
	return i, err
}

const getTrackFromId = `-- name: GetTrackFromId :one
SELECT id, youtubeid, name, spotifyduration, spotifyuri, isexplicit, isavailable, youtubeurltype, youtubeurl, fileurl, albumid, created_on, updated_on, spotifyid, tracknumber FROM tracks WHERE id=$1 LIMIT 1
`

func (q *Queries) GetTrackFromId(ctx context.Context, id uuid.UUID) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrackFromId, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Youtubeid,
		&i.Name,
		&i.Spotifyduration,
		&i.Spotifyuri,
		&i.Isexplicit,
		&i.Isavailable,
		&i.Youtubeurltype,
		&i.Youtubeurl,
		&i.Fileurl,
		&i.Albumid,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Spotifyid,
		&i.Tracknumber,
	)
	return i, err
}

const insertAlbumTrack = `-- name: InsertAlbumTrack :one
INSERT INTO tracks (id, isAvailable,name, trackNumber,spotifyId,spotifyDuration, spotifyUri, isExplicit, albumId, youtubeid)
VALUES (GEN_RANDOM_UUID(), TRUE, $1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, youtubeid, name, spotifyduration, spotifyuri, isexplicit, isavailable, youtubeurltype, youtubeurl, fileurl, albumid, created_on, updated_on, spotifyid, tracknumber
`

type InsertAlbumTrackParams struct {
	Name            string
	Tracknumber     sql.NullInt32
	Spotifyid       sql.NullString
	Spotifyduration sql.NullInt32
	Spotifyuri      sql.NullString
	Isexplicit      sql.NullBool
	Albumid         sql.NullString
	Youtubeid       sql.NullString
}

func (q *Queries) InsertAlbumTrack(ctx context.Context, arg InsertAlbumTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, insertAlbumTrack,
		arg.Name,
		arg.Tracknumber,
		arg.Spotifyid,
		arg.Spotifyduration,
		arg.Spotifyuri,
		arg.Isexplicit,
		arg.Albumid,
		arg.Youtubeid,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Youtubeid,
		&i.Name,
		&i.Spotifyduration,
		&i.Spotifyuri,
		&i.Isexplicit,
		&i.Isavailable,
		&i.Youtubeurltype,
		&i.Youtubeurl,
		&i.Fileurl,
		&i.Albumid,
		&i.CreatedOn,
		&i.UpdatedOn,
		&i.Spotifyid,
		&i.Tracknumber,
	)
	return i, err
}

const insertTrackFileURL = `-- name: InsertTrackFileURL :exec
UPDATE tracks SET fileUrl= $2 WHERE (id= $1)
`

type InsertTrackFileURLParams struct {
	ID      uuid.UUID
	Fileurl sql.NullString
}

func (q *Queries) InsertTrackFileURL(ctx context.Context, arg InsertTrackFileURLParams) error {
	_, err := q.db.ExecContext(ctx, insertTrackFileURL, arg.ID, arg.Fileurl)
	return err
}

const insertTrackYoutubeUrl = `-- name: InsertTrackYoutubeUrl :exec
UPDATE tracks SET youtubeUrl= $2 WHERE (id=$1)
`

type InsertTrackYoutubeUrlParams struct {
	ID         uuid.UUID
	Youtubeurl sql.NullString
}

func (q *Queries) InsertTrackYoutubeUrl(ctx context.Context, arg InsertTrackYoutubeUrlParams) error {
	_, err := q.db.ExecContext(ctx, insertTrackYoutubeUrl, arg.ID, arg.Youtubeurl)
	return err
}
