// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: useralbum.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserRecentlyVisitedAlbums = `-- name: GetUserRecentlyVisitedAlbums :many
SELECT albums.name, albums.id, albums.coverimageurl, albums.releasedate, albums.numberoftracks FROM user_album 
INNER JOIN albums ON user_album.albumId=albums.id WHERE userId = $1 ORDER BY user_album.created_on DESC LIMIT 10
`

type GetUserRecentlyVisitedAlbumsRow struct {
	Name           string
	ID             string
	Coverimageurl  sql.NullString
	Releasedate    sql.NullString
	Numberoftracks int32
}

func (q *Queries) GetUserRecentlyVisitedAlbums(ctx context.Context, userid uuid.NullUUID) ([]GetUserRecentlyVisitedAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRecentlyVisitedAlbums, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRecentlyVisitedAlbumsRow
	for rows.Next() {
		var i GetUserRecentlyVisitedAlbumsRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.Coverimageurl,
			&i.Releasedate,
			&i.Numberoftracks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUserVisitedAlbum = `-- name: SaveUserVisitedAlbum :exec
INSERT INTO user_album (id, userId, albumId, isSaved)
VALUES (GEN_RANDOM_UUID(), $1, $2, TRUE)
`

type SaveUserVisitedAlbumParams struct {
	Userid  uuid.NullUUID
	Albumid sql.NullString
}

func (q *Queries) SaveUserVisitedAlbum(ctx context.Context, arg SaveUserVisitedAlbumParams) error {
	_, err := q.db.ExecContext(ctx, saveUserVisitedAlbum, arg.Userid, arg.Albumid)
	return err
}
