// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID             string
	Name           string
	Coverimageurl  sql.NullString
	Releasedate    sql.NullString
	Artists        sql.NullString
	Spotifyurl     sql.NullString
	Jsontracklist  sql.NullString
	CreatedOn      time.Time
	UpdatedOn      time.Time
	Numberoftracks int32
}

type Track struct {
	ID              uuid.UUID
	Youtubeid       sql.NullString
	Name            string
	Spotifyduration sql.NullInt32
	Spotifyuri      sql.NullString
	Isexplicit      sql.NullBool
	Isavailable     bool
	Youtubeurltype  sql.NullString
	Youtubeurl      sql.NullString
	Fileurl         sql.NullString
	Albumid         sql.NullString
	CreatedOn       time.Time
	UpdatedOn       time.Time
}

type User struct {
	ID        uuid.UUID
	Username  sql.NullString
	Email     string
	Password  string
	Authtype  string
	CreatedOn time.Time
	UpdatedOn time.Time
}

type UserAlbum struct {
	ID           uuid.UUID
	Userid       uuid.NullUUID
	Albumid      sql.NullString
	Issaved      sql.NullBool
	Isdownloaded sql.NullBool
}
