name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Add execution on dependencies script
        run: chmod +x ./dependencies.sh

      - name: Install Dependencies
        run: ./dependencies.sh
      
      - name: Add current_dir to path variable
        run: echo $GITHUB_WORKSPACE >> $GITHUB_PATH
        
      - name: Run server tests
        run: go test ./...
        working-directory: server

    env:
      SPOTIFY_CLIENTID: ${{secrets.SPOTIFY_CLIENTID}}
      SPOTIFY_CLIENTSECRET: ${{secrets.SPOTIFY_CLIENTSECRET}}
      PORT: 8000
      YOUTUBE_APIKEY: ${{secrets.YOUTUBE_APIKEY}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}

